## Business Question
    What is the total revenue?
    How are monthly sales changing?
    Which product categories generate the most revenue?
    Which states and cities contribute the highest sales?
    What is the Average Order Value (AOV)?
    Which months have peak sales?
    Which products sell the most?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import os

In [2]:
from sqlalchemy import create_engine

#connect to server
engine = create_engine(
    "postgresql://postgres:12345@localhost:5432/Olist_DB")

## Load to SQL

In [3]:
# import pandas as pd
# import os
# from sqlalchemy import create_engine

# #connect to server
# engine = create_engine(
#     "postgresql://postgres:12345@localhost:5432/Olist_DB")


# #function
# def load_to_postgres(df , table , engine) :
#     """ Here we load data from dir to SQL"""
#     df.to_sql(table, con= engine , if_exists="replace" , index = False)

# #find file by os
# for file in os.listdir(r"d:\Projects\sales analysis\Dataset") :
#     df = pd.read_csv(f"d:\Projects\sales analysis\Dataset\{file}")
#     # load_to_postgres(df,file[:-4],engine)
# print(f"Data load successfully !!!")
 
#___________________________________________________________________________________________________________________________________

# script
from ingestion import Load_data
Load_data()

## Access data from SQL

In [4]:
# name of tables
from sqlalchemy import inspect
inspector = inspect(engine)
tables = inspector.get_table_names()
print(tables)

['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_orders_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation']

In [5]:
for table in tables :
    print(table)
    print(pd.read_sql(F"SELECT COUNT(*) FROM {table}",engine)['count'].values[0])
    df = pd.read_sql(F"SELECT * FROM {table}",engine)
    print(df.columns)
    display(df.head(3))

olist_customers_dataset
99441
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

olist_geolocation_dataset
1000163
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

olist_orders_dataset
99441
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

olist_order_items_dataset
112650
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

olist_order_payments_dataset
103886
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

olist_order_reviews_dataset
99224
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,None,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,None,2018-02-17 00:00:00,2018-02-18 14:36:24

olist_products_dataset
32951
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

olist_sellers_dataset
3095
Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

product_category_name_translation
71
Index(['product_category_name', 'product_category_name_english'], dtype='object')

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

### 1. What is the total revenue?

In [6]:
quary = """SELECT * from olist_orders_dataset od join olist_order_payments_dataset op on od.order_id = op.order_id 
                                   WHERE od.order_status = 'delivered' ; """
revenue = pd.read_sql(quary, engine)
revenue["payment_value"].sum()

np.float64(15422461.77)

### 2. How are monthly sales changing?

In [32]:
import matplotlib.pyplot as plt

quary = """SELECT
    TO_CHAR(
        DATE_TRUNC('month', o.order_purchase_timestamp::TIMESTAMP),
        'YYYY-MM'
    ) AS month,
    ROUND(SUM(op.payment_value)::NUMERIC, 2) AS revenue
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset op
    ON o.order_id = op.order_id
WHERE o.order_status = 'delivered'
GROUP BY DATE_TRUNC('month', o.order_purchase_timestamp::TIMESTAMP)
ORDER BY DATE_TRUNC('month', o.order_purchase_timestamp::TIMESTAMP); """
revenue = pd.read_sql(quary, engine)
revenue.head()

# plt.bar(revenue['month'] , revenue['revenue'] , )
# plt.xlabel('months')
# plt.xticks(rotation=45)   # try 45 or 90 degrees
# plt.tight_layout()        # adjusts spacing so labels fit
# plt.show()

     month    revenue
0  2016-10   46566.71
1  2016-12      19.62
2  2017-01  127545.67
3  2017-02  271298.65
4  2017-03  414369.39

### 3.Which product categories generate the most revenue?

In [8]:
quary = """SELECT  pc.product_category_name_english,ROUND(SUM(od.price)::NUMERIC, 2) as revenue from product_category_name_translation pc join olist_products_dataset pd on pc.product_category_name = pd.product_category_name
            join olist_order_items_dataset od on od.product_id = pd.product_id left join olist_orders_dataset o on o.order_id= od.order_id where order_status = 'delivered' 
             GROUP BY pc.product_category_name_english  ORDER BY revenue DESC; """
catagory_wise_revenue = pd.read_sql(quary, engine)
catagory_wise_revenue.head()

  product_category_name_english     revenue
0                 health_beauty  1233131.72
1                 watches_gifts  1166176.98
2                bed_bath_table  1023434.76
3                sports_leisure   954852.55
4         computers_accessories   888724.61

### 4.Which states and cities contribute the highest sales?

## Highest sales States

In [9]:
## here we calculate the actual revenue as per the goods only here not calculate the any other charges or payment settlement. 

quary1 = """ Select c.customer_state,sum(op.price) as actual_rev 
from olist_customers_dataset c 
              join olist_orders_dataset od 
              on c.customer_id = od.customer_id join olist_order_items_dataset 
              op on od.order_id = op.order_id where od.order_status = 'delivered' 
              group by c.customer_state order by sum(op.price) DESC ;  """ 



## here we calculate revenue as per how money we get from the customer , where shipping charges and other charges or settlements are included
quary = """ SELECT
    c.customer_state,
    round(SUM(op.payment_value::NUMERIC),2) AS revenue
FROM olist_customers_dataset c
JOIN olist_orders_dataset o
    ON c.customer_id=o.customer_id
JOIN olist_order_payments_dataset op
    ON o.order_id=op.order_id
WHERE o.order_status='delivered'
GROUP BY c.customer_state
ORDER BY revenue DESC; """


state_wise1 = pd.read_sql(quary1,engine)

state_wise = pd.read_sql(quary,engine)
new  = pd.concat([state_wise,state_wise1['actual_rev']] , axis = 1)
new.head()

  customer_state     revenue    actual_rev
0             SP  5770266.19  5.067633e+06
1             RJ  2055690.45  1.759651e+06
2             MG  1819277.61  1.552482e+06
3             RS   861802.40  7.288975e+05
4             PR   781919.55  6.660635e+05

In [10]:
## here we calculate the actual revenue as per the goods only here not calculate the any other charges or payment settlement. 

quary1 = """ Select c.customer_city,sum(op.price) as actual_rev 
from olist_customers_dataset c 
              join olist_orders_dataset od 
              on c.customer_id = od.customer_id join olist_order_items_dataset 
              op on od.order_id = op.order_id where od.order_status = 'delivered' 
              group by c.customer_city order by sum(op.price) DESC ;  """ 



## here we calculate revenue as per how money we get from the customer , where shipping charges and other charges or settlements are included
quary = """ SELECT
    c.customer_city,
    round(SUM(op.payment_value::NUMERIC),2) AS revenue
FROM olist_customers_dataset c
JOIN olist_orders_dataset o
    ON c.customer_id=o.customer_id
JOIN olist_order_payments_dataset op
    ON o.order_id=op.order_id
WHERE o.order_status='delivered'
GROUP BY c.customer_city
ORDER BY revenue DESC; """


city_wise1 = pd.read_sql(quary1,engine)

city_wise = pd.read_sql(quary,engine)
new  = pd.concat([city_wise,city_wise1['actual_rev']] , axis = 1)
new.head()

    customer_city     revenue  actual_rev
0       sao paulo  2108162.22  1859556.83
1  rio de janeiro  1111872.32   955573.97
2  belo horizonte   406050.87   346039.04
3        brasilia   345221.87   295814.72
4        curitiba   238582.26   205999.33

### 5.What is the Average Order Value (AOV)?

In [11]:
quary = """SELECT
    ROUND(AVG(order_total),2) AS average_order_value
FROM
(
    SELECT
        o.order_id,
        SUM(op.payment_value :: numeric) AS order_total
    FROM olist_orders_dataset o
    JOIN olist_order_payments_dataset op
        ON o.order_id=op.order_id
    WHERE o.order_status='delivered'
    GROUP BY o.order_id
) t; """
average_ov = pd.read_sql(quary, engine)
average_ov.head()

   average_order_value
0               159.86

### 7. Which Months Have Peak Sales?

In [40]:
quary = """SELECT
    TO_CHAR(TO_TIMESTAMP(order_purchase_timestamp,'YYYY-MM-DD HH24:MI:SS'),'Month') AS month_name,
    ROUND(SUM(payment_value :: numeric),2) AS revenue
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p
ON o.order_id=p.order_id
WHERE order_status='delivered'
GROUP BY month_name
ORDER BY revenue DESC ; """
average_ov = pd.read_sql(quary, engine)
average_ov.head()

  month_name     revenue
0  May        1695903.42
1  August     1631414.89
2  July       1594307.79
3  March      1535047.39
4  April      1523886.13

### 8. Which Products Sell the Most?

In [13]:
quary = """ select ct.product_category_name_english , count(*) as total_sale from olist_order_items_dataset oi 
            inner join olist_orders_dataset od on oi.order_id = od.order_id 
            join olist_products_dataset op on op.product_id = oi.product_id
            join product_category_name_translation ct on ct.product_category_name = op.product_category_name
            where od.order_status = 'delivered'
            group by ct.product_category_name_english 
            order by total_sale DESC"""



total_sales = pd.read_sql(quary ,engine)
total_sales.head()

  product_category_name_english  total_sale
0                bed_bath_table       10953
1                 health_beauty        9465
2                sports_leisure        8431
3               furniture_decor        8160
4         computers_accessories        7644

In [101]:
quary = """
SELECT
    o.order_id,
    o.order_purchase_timestamp,
    o.order_status,

    c.customer_unique_id,
    c.customer_city,
    c.customer_state,

    oi.product_id,
    p.product_category_name,

    oi.seller_id,
    s.seller_city,
    s.seller_state,

    oi.price,
    oi.freight_value,

    pay.payment_type,
    pay.payment_installments,
    pay.payment_value,

    r.review_score,

    o.order_delivered_customer_date,
    o.order_estimated_delivery_date

FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
JOIN olist_products_dataset p
    ON oi.product_id = p.product_id
JOIN olist_sellers_dataset s
    ON oi.seller_id = s.seller_id
LEFT JOIN olist_order_payments_dataset pay
    ON o.order_id = pay.order_id
LEFT JOIN olist_order_reviews_dataset r
    ON o.order_id = r.order_id;"""


summury = pd.read_sql(quary,engine)
summury.to_sql("summury",con=engine,if_exists="replace",index=False)

310

In [102]:
quary = """ select * from summury"""
pd.read_sql(quary ,engine)

,order_id,order_purchase_timestamp,order_status,customer_unique_id,customer_city,customer_state,product_id,product_category_name,seller_id,seller_city,seller_state,price,freight_value,payment_type,payment_installments,payment_value,review_score,order_delivered_customer_date,order_estimated_delivery_date
0,00018f77f2f0320c557190d7a144bdd3,2017-04-26 10:53:06,delivered,eb28e67c4c0b83846050ddfb8a35d051,santa fe do sul,SP,e5f2d52b802189ee658865ca93d83a8f,pet_shop,dd7ddc04e1b6c2c614352b383efe2d36,sao paulo,SP,239.90,19.93,credit_card,3.0,259.83,4.0,2017-05-12 16:04:24,2017-05-15 00:00:00
1,000229ec398224ef6ca0657da4fc703e,2018-01-14 14:33:31,delivered,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,c777355d18b72b67abbeef9df44fd0fd,moveis_decoracao,5b51032eddd242adc84c38acab88f23d,borda da mata,MG,199.00,17.87,credit_card,5.0,216.87,5.0,2018-01-22 13:19:16,2018-02-05 00:00:00
2,00048cc3ae777c65dbb7d2a0634bc1ea,2017-05-15 21:42:34,delivered,85c835d128beae5b4ce8602c491bf385,uberaba,MG,ef92defde845ab8450f9d70c526ef70f,utilidades_domesticas,6426d21aca402a131fc0a5d0960a3c90,ribeirao preto,SP,21.90,12.69,boleto,1.0,34.59,4.0,2017-05-22 13:44:35,2017-06-06 00:00:00
3,0005a1a1728c9d785b8e2b08b904576c,2018-03-19 18:40:33,delivered,639d23421f5517f69d0c3d6e6564cf0e,santos,SP,310ae3c140ff94b03219ad0adc3c778f,beleza_saude,a416b6a846a11724393025641d4edd5e,sao paulo,SP,145.95,11.65,credit_card,3.0,157.60,1.0,2018-03-29 18:17:31,2018-03-29 00:00:00
4,00061f2a7bc09da83e415a52dc8a4af1,2018-03-24 22:16:10,delivered,107e6259485efac66428a56f10801f4f,piracicaba,SP,d63c1011f49d98b976c352955b1c4bea,beleza_saude,cc419e0650a3c5ba77189a1882b7556a,santo andre,SP,59.99,8.88,credit_card,3.0,68.87,5.0,2018-03-29 00:04:19,2018-04-09 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118305,f247ddbea2a3d9e88b688d08f946db4c,2018-01-16 01:25:39,shipped,e715d72ff36112e6b739623648bd6802,sao paulo,SP,ef7352a2d8b4adc975b83c8e8c23da5c,esporte_lazer,729b2d09b2a0bdab221076327f13d050,mineiros do tiete,SP,16.90,11.85,credit_card,1.0,28.75,1.0,None,2018-02-06 00:00:00
118306,f24bbebc2c8ba687b65f1be751dd8982,2018-02-20 18:27:39,delivered,c52d06680b82af13464722a1abe3634a,sao goncalo,RJ,1060d9ab6b911bfce1439c25afcd790b,informatica_acessorios,4e5725ba188db8252977a4f0227bd462,ribeirao preto,SP,29.90,15.10,credit_card,1.0,45.00,1.0,2018-04-19 16:49:31,2018-03-14 00:00:00
118307,f24f489f04a7f74d2ca01d753ff8e38c,2018-03-09 11:30:19,delivered,3a85db39310d85fe317589a36c16c1a3,conselheiro lafaiete,MG,99a4788cb24856965c36a24e339b6058,cama_mesa_banho,4a3ca9315b744ce9f8e9374361493884,ibitinga,SP,86.90,19.95,credit_card,6.0,106.85,5.0,2018-04-07 18:13:30,2018-04-16 00:00:00
118308,f2597992f6da6f545223c8f3aac0a681,2017-12-06 11:19:14,delivered,2e3c1ec925c0e468eea4848e1502ac1b,osasco,SP,2f5e485bacfeb554bec55cd497c9bc51,utilidades_domesticas,4830e40640734fc1c52cd21127c341d4,sao paulo,SP,45.99,7.78,boleto,1.0,53.77,5.0,2017-12-09 17:33:33,2017-12-22 00:00:00
118309,f25d0a9da957de7ffe36398088651d59,2018-01-25 02:10:55,delivered,1e69a7ade061300184ff903107daa599,recife,PE,71137504070dc94a0e1d04089985f3e2,esporte_lazer,440dd6ab244315c632130ecfb63827b1,votuporanga,SP,114.90,33.25,credit_card,2.0,148.15,5.0,2018-02-04 16:13:07,2018-03-01 00:00:00